services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3800:3800'
    environment: 
      NODE_ENV: development
      APP_NAME: PINGER
      APP_DEV_URL: http://localhost:3800
      MAIL_SERVICE: gmail

      MAILER_HOST: smtp.gmail.com
      MAILER_PORT: 465

    env_file:
      - .env
    command: ["yarn", "start:prod"]
